### ISSUE TITLE
"NBFT: jq error while processing ".host_name" message in boot log.

### ISSUE THREAD

**Issue by charles-rose** [timberland-sig/dracut#4]
**Describe the bug**
System displays this message during boot:
NBFT: jq error while processing ".host_name"

**Distribution used**
OpenSUSE Leap

**Dracut version**
dracut-055+suse.345.g8b8708cb-150500.1.3 with https://github.com/timberland-sig/dracut/pull/3

**Init system**
systemd

**To Reproduce**
Configure NVMe-oF TCP in system BIOS and boot system to OS installer.

**Expected behavior**
No NBFT or dracut errors during boot.

**Additional context**
This occurs because ".host_name" is not present on this system:
"hfi":[
{
"index":1,
"transport":"tcp",
"pcidev":"0:1:0.0",
"mac_addr":"ec:2a:72:33:06:cc",
"vlan":0,
"ip_origin":82,
"ipaddr":"100.68.144.67",
"subnet_mask_prefix":24,
"gateway_ipaddr":"100.68.144.254",
"route_metric":500,
"primary_dns_ipaddr":"100.64.0.111",
"secondary_dns_ipaddr":"10.228.254.66",
"dhcp_server_ipaddr":"100.64.0.11",
"this_hfi_is_default_route":1,
"dhcp_override":1
}

This is a benign message. Empty IP addresses are checked with nbft_check_empty_address, something similar for strings would be nice.

**Comment by mwilck** [comment]
This is [fixed](https://github.com/timberland-sig/dracut/blob/80b2f84b76f81c340e6eb75c2b5feb2557615521/modules.d/95nvmf/parse-nvmf-boot-connections.sh#L186) after "merging" #6.
